### ISSUE TITLE
Hydra2 Rpi3: getJdbcSQLException

### ISSUE THREAD

**Issue by jflecool2** [petersendev/hassio-addons#104]
Fresh install of Hydra2 generate an infinite loop of error. I am not sure if its your repo or Hydra2 is broken. Google doesnt seem to have many answer for this... 
`
12:02:27.939 [main] DEBUG org.nzbhydra.NzbHydra - Setting property browser.disabled to value true
12:02:28.005 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.port to 5076
12:02:28.010 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.ssl to false
12:02:28.012 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.databaseRetentionTime to 1000
12:02:28.014 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.consolelevel to INFO
12:02:28.017 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.logging.logMaxHistory to 30
12:02:30.140 [main] ERROR org.nzbhydra.NzbHydra - An unexpected error occurred during startup
select "script", "checksum" from "schema_version"; [42102-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.command.Parser.readTableFilter(Parser.java:1970)
	at org.h2.command.Parser.parseSelect(Parser.java:2959)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:2649)
	at org.h2.command.Parser.parsePrepared(Parser.java:868)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.nzbhydra.database.DatabaseRecreation.isDatabaseRecreationNotNeeded(DatabaseRecreation.java:92)
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
select "script", "checksum" from "schema_version"; [42102-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.command.Parser.readTableFilter(Parser.java:1970)
	at org.h2.command.Parser.parseSelect(Parser.java:2959)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:2649)
	at org.h2.command.Parser.parsePrepared(Parser.java:868)
	at org.h2.command.Parser.parse(Parser.java:815)
	at org.h2.engine.Session.prepareLocal(Session.java:657)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
	at org.nzbhydra.database.DatabaseRecreation.isDatabaseRecreationNotNeeded(DatabaseRecreation.java:92)
	at org.nzbhydra.NzbHydra.startup(NzbHydra.java:192)
	... 8 more
2021-12-09 12:02:30,228  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it
Logging wrapper output to /config/hydra2/logs/wrapper.log
2021-12-09 12:02:31,693  INFO - Determined java version as '11' from version string 'openjdk version "11.0.11" 2021-04-20'
2021-12-09 12:02:31,697  INFO - Starting NZBHydra main process with command line: java -Xmx256M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/config/hydra2/logs -Dspring.output.ansi.enabled=ALWAYS -jar /app/nzbhydra2/bin/lib/core-3.18.1-exec.jar --nobrowser --datafolder /config/hydra2 in folder /app/nzbhydra2/bin
12:02:38.710 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-3.18.1-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep007to008.class]
12:02:38.725 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-3.18.1-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep005to006.class]
12:02:38.731 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-3.18.1-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep003to004.class]
12:02:38.736 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-3.18.1-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep004to005.class]
12:02:38.741 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-3.18.1-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep014to015.class]
12:02:38.746 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-3.18.1-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep012to013.class]
12:02:38.750 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-3.18.1-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep015to016.class]
12:02:38.754 [main] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: URL [jar:file:/app/nzbhydra2/bin/lib/core-3.18.1-exec.jar!/BOOT-INF/classes!/org/nzbhydra/config/migration/ConfigMigrationStep011to012.class]
12:02:39.779 [main] DEBUG org.nzbhydra.config.ConfigReaderWriter - Writing to file /config/hydra2/nzbhydra.yml
12:02:39.902 [main] DEBUG org.nzbhydra.NzbHydra - Setting property browser.disabled to value true
12:02:39.961 [main] DEBUG org.nzbhydra.NzbHydra - Setting main.port to 5076`

**Comment by jflecool2** [comment]
Once I realized uninstalling didnt remove config and tried re-installing with config deleted, everything worked as intended. Maybe i corrupted something somehow. Thanks
