### ISSUE TITLE
jellyfin addon does not start - Access to the path '/share/jellyfin/data/data' is denied.

### ISSUE THREAD

**Issue by Weedalf** [petersendev/hassio-addons#123]
Hello i cannot start The Jellyfin addon. Log says Access to the path '/share/jellyfin/data/data' is denied.

My setup is a Raspberry Pi 4b with 4gb RAM running Home Assistant OS. I just installed Home assistant and tried to run jellyfin.

```
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/share/jellyfin/data/data' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Emby.Server.Implementations.AppBase.BaseApplicationPaths..ctor(String programDataPath, String logDirectoryPath, String configurationDirectoryPath, String cacheDirectoryPath, String webDirectoryPath)
   at Emby.Server.Implementations.ServerApplicationPaths..ctor(String programDataPath, String logDirectoryPath, String configurationDirectoryPath, String cacheDirectoryPath, String webDirectoryPath)
   at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
```

**Comment by Weedalf** [comment]
I tested the emby addon and this is was running without any problems.

**Comment by bencorrado** [comment]
I am also running into this same error on a x86_64 NUC.
```
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/share/jellyfin/data/data' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Emby.Server.Implementations.AppBase.BaseApplicationPaths..ctor(String programDataPath, String logDirectoryPath, String configurationDirectoryPath, String cacheDirectoryPath, String webDirectoryPath)
   at Emby.Server.Implementations.ServerApplicationPaths..ctor(String programDataPath, String logDirectoryPath, String configurationDirectoryPath, String cacheDirectoryPath, String webDirectoryPath)
   at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)```

**Comment by felislynx-silae** [comment]
Same here on x86_64 pc with HaOS
